version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: EST
  open-pull-requests-limit: 10
  reviewers:
  - mkholjuraev
  allow:
  - dependency-name: "@redhat-cloud-services/frontend*"
  - dependency-name: "@patternfly/*"
    dependency-type: direct
  ignore:
  - dependency-name: "@patternfly/react-table"
    versions:
    - 4.20.15
    - 4.24.1
  - dependency-name: "@redhat-cloud-services/frontend-components-config"
    versions:
    - 3.0.0-beta20
    - 3.0.0-beta23
    - 4.0.1
    - 4.0.11
    - 4.0.19
    - 4.0.21
    - 4.0.6
  - dependency-name: "@redhat-cloud-services/frontend-components-remediations"
    versions:
    - 2.3.10
    - 3.1.9
  - dependency-name: "@patternfly/react-core"
    versions:
    - 4.101.3
    - 4.106.1
    - 4.90.1
    - 4.90.2
    - 4.97.2
  - dependency-name: "@redhat-cloud-services/frontend-components"
    versions:
    - 3.0.1
    - 3.0.10
    - 3.0.2
    - 3.0.4
    - 3.0.5
    - 3.0.6
    - 3.0.8
    - 3.1.0
    - 3.1.3
    - 3.1.4
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: "@patternfly/react-icons"
    versions:
    - 4.8.3
    - 4.8.4
    - 4.9.2
    - 4.9.5
  - dependency-name: "@redhat-cloud-services/frontend-components-notifications"
    versions:
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
  - dependency-name: "@redhat-cloud-services/frontend-components-utilities"
    versions:
    - 3.0.2
    - 3.0.3
    - 3.1.1
