version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
    ignore:
      - dependency-name: "@patternfly/react-core"
        versions: ["7.x.x"]
      - dependency-name: "@patternfly/react-icons"
        versions: ["7.x.x"]
      - dependency-name: "@patternfly/react-table"
        versions: ["7.x.x"]
      - dependency-name: "react-router-dom"
        versions: ["7.x.x"]
      - dependency-name: "@redhat-cloud-services/frontend-components-utilities"
        versions: ["8.x.x"]
      - dependency-name: "@redhat-cloud-services/frontend-components"
        versions: ["8.x.x"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "htmlparser2"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jest-environment-jsdom"
        update-types: ["version-update:semver-major"]
       # eslint-plugin-react is not yet compatible with ESLint 10 (context API)
       # TODO: Revert this change when possible (HMS-10187)
       - dependency-name: "eslint"
         update-types: ["version-update:semver-major"]
       - dependency-name: "@eslint/js"
         update-types: ["version-update:semver-major"]
    groups:
      fec:
        patterns:
          - "@redhat-cloud-services/*"
        exclude-patterns:
          - "@redhat-cloud-services/*-client"
      patternfly:
        patterns:
          - "@patternfly/*"
        exclude-patterns:
          - "@patternfly/react-charts"
        update-types:
          - "minor"
          - "patch"
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      lint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "stylelint*"
      clients:
        patterns:
          - "@redhat-cloud-services/*-client"
      jest:
        patterns:
          - "jest*"
      cypress:
        patterns:
          - "*cypress*"
      react:
        patterns:
          - "react"
          - "react-dom"
      webpack:
        patterns:
          - "webpack"
          - "webpack-bundle-analyzer"
      npm:
        patterns:
          - "*"
