name: 'UI: Playwright Tests'
on:
  pull_request:
    types: [ opened, reopened, synchronize, labeled, unlabeled ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  playwright-ui-tests:
    runs-on:
      - codebuild-patch-frontend-${{ github.run_id }}-${{ github.run_attempt }}
      - instance-size:large
      - buildspec-override:true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Create front-end .env file
        run: |
          # Check if the secrets are set
          if [ -z "$ADMIN_USERNAME" ]; then
            echo "Error: ADMIN_USERNAME secret is not set."
            exit 1
          fi

          if [ -z "$ADMIN_PASSWORD" ]; then
            echo "Error: ADMIN_PASSWORD secret is not set."
            exit 1
          fi

          # Create the .env file and write the secrets and other variables to it
          {
            echo "ADMIN_USERNAME=$ADMIN_USERNAME"
            echo "ADMIN_PASSWORD=$ADMIN_PASSWORD"
            echo "BASE_URL=https://stage.foo.redhat.com:1337"
            echo "CI=true"
          } >> .env

          echo ".env file created successfully."

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Cache - node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            dist
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-frontend-node-modules-

      # This prevents an error related to minimum watchers when running the front-end and playwright
      - name: Increase file watchers limit
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Install dependecies
        run: 'npm ci && npm run build && npx playwright install chromium --only-shell'

      - name: Update /etc/hosts
        run: sudo npx fec patch-etc-hosts

      - name: Frontend run (static)
        run: npx fec static --port 8003 &

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:8003/apps/patch/

      - name: Run testing proxy
        run: docker run -d --network=host -e HTTPS_PROXY=$RH_PROXY_URL -e ROUTES_JSON_PATH=/config/routes-ci.json -v "$(pwd)/config:/config:ro,Z"  --name frontend-development-proxy quay.io/redhat-user-workloads/hcc-platex-services-tenant/frontend-development-proxy:latest

      - name: Run front-end Playwright tests
        run: CURRENTS_PROJECT_ID=nKL5NV CURRENTS_RECORD_KEY=$CURRENTS_RECORD_KEY CURRENTS_CI_BUILD_ID="${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}" npx playwright test

      - name: Publish front-end Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './playwright-ctrf/playwright-ctrf.json'

      - name: Store front-end Test report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
